core/courier/urls.py
from django.urls import path
from .views import (
    courier_index,
    courier_profile,
    courier_available_jobs,
    courier_available_job,
    courier_current_job,
    courier_current_job_camera,
    courier_job_completed,
    courier_archived_jobs,
    courier_payment_method,
)
from .apis import courier_available_jobs_api, courier_current_job_update_api, courier_fcm_token_update_api

app_name = "courier"

urlpatterns = [
    path("", courier_index, name="home"),
    path("profile/", courier_profile, name="profile"),
    path("payment/", courier_payment_method, name="payment"),
    path("jobs/", courier_available_jobs, name="available_jobs"),
    path("jobs/current/", courier_current_job, name="current_job"),
    path("jobs/completed/", courier_job_completed, name="completed_job"),
    path("jobs/archived/", courier_archived_jobs, name="archived_jobs"),
    path("jobs/<str:pk>/", courier_available_job, name="available_job_details"),
    path(
        "jobs/current/<str:pk>/camera/",
        courier_current_job_camera,
        name="current_job_camera",
    ),
    path("api/jobs/", courier_available_jobs_api, name="available_jobs_api"),
    path(
        "api/jobs/current/<str:pk>/update/",
        courier_current_job_update_api,
        name="current_job_update_api",
    ),
    path(
        "api/fcm-token/update/",
        courier_fcm_token_update_api,
        name="fcm_token_update_api",
    ),
]

taskrabbit/urls.py
"""
taskrabbit URL Configuration
"""
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from core.views import index, sign_up
import core.customer.urls
import core.courier.urls

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index),
    path("sign-in/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("sign-up", sign_up, name="sign_up"),
    path('accounts/', include('allauth.urls')),
    path("customer/", include(core.customer.urls, namespace="customer")),
    path("courier/", include(core.courier.urls, namespace="courier")),
    path(
        "firebase-messaging-sw.js",
        (
            TemplateView.as_view(
                template_name="firebase-messaging-sw.js",
                content_type="application/x-javascript",
            )
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_firebase-app.html
{% load get_env %}

<script type="module">
    import { initializeApp } from "https://www.gstatic.com/firebasejs/9.17.2/firebase-app.js";
    const firebaseConfig = {
        apiKey: "{% get_env_var 'APIKEY' %}",
        authDomain: "task-rabbit-7d031.firebaseapp.com",
        projectId: "task-rabbit-7d031",
        storageBucket: "task-rabbit-7d031.appspot.com",
        messagingSenderId: "363527763746",
        appId: "1:363527763746:web:9eeb354ecbdc1b238a177b"
    };
    
    // Initialize Firebase
    const app = initializeApp(firebaseConfig);
</script>

templates/partials/_firebase-auth.html
<script type="module">
    import { getAuth, RecaptchaVerifier, signInWithPhoneNumber } from "https://www.gstatic.com/firebasejs/9.17.2/firebase-auth.js"; 
    
    const get_otp_code_block = document.querySelector('#get-otp-code')
    const set_otp_code_block = document.querySelector('#set-otp-code')
    const get_otp_btn = document.querySelector('#get-otp-code button')
    const set_otp_btn = document.querySelector('#set-otp-code button')
    const get_phone_no = document.querySelector('#get-otp-code input')
    const get_otp_code = document.querySelector('#set-otp-code input')
    const change_phone_number = document.querySelector('#change-phone')
    const change_phone_numbe_btn = document.querySelector('#change-phone button')

    const auth = getAuth();
    
    const onVerify = (idToken) => {
        let form = document.createElement('form')
        form.method = "POST"

        let input_1 = document.createElement("input")
        input_1.classList.add('form-control')
        input_1.name = "id_token";
        input_1.value = idToken
        form.appendChild(input_1)
        
        let input_2 = document.createElement("input")
        input_2.name = "action";
        input_2.value = "update_phone"
        form.appendChild(input_2)
        
        let input_3 = document.createElement("input")
        input_3.name = "csrfmiddlewaretoken";
        input_3.value = "{{ csrf_token }}"
        form.appendChild(input_3)

        document.body.appendChild(form);
        form.submit()
    }

    window.recaptchaVerifier = new RecaptchaVerifier('recaptcha-container', 
        {
            'size': 'invisible',
        }, 
        auth
    );


    if (get_otp_code_block !== null) {
        if (get_otp_btn !== null) {
            get_otp_btn.addEventListener('click', () => {
                if (get_phone_no !== null) {
                    const phoneNumber = get_phone_no.value
                    console.log(phoneNumber)
                    const appVerifier = window.recaptchaVerifier;
                    signInWithPhoneNumber(auth, phoneNumber, appVerifier)
                        .then((confirmationResult) => {
                        window.confirmationResult = confirmationResult;
                        get_otp_code_block.classList.add('d-none')
                        set_otp_code_block.classList.remove('d-none')
                    }).catch((error) => {
                        console.log(error)
                    });
                    
                }
            })
        }
    }
    
    if (set_otp_code_block !== null) {
        set_otp_btn?.addEventListener('click', () => {
            if (get_otp_code !== null) {
                const code = get_otp_code.value
                confirmationResult.confirm(code).then((result) => {
                    const user = result.user;
                    user.getIdToken().then((idToken) => {
                        onVerify(idToken)
                    })
                }).catch((error) => {
                    console.log(error)
                });
            } else {
                console.log('error')
            }
        })
    }

    if (change_phone_number !== null) {
        if (change_phone_numbe_btn !== null) {
            change_phone_numbe_btn.addEventListener('click', () => {
                change_phone_number.classList.add('d-none')
                get_otp_code_block.classList.remove('d-none')
            })
        }
    }
</script>

templates/partials/_firebase-messaging.html
{% load get_env %}

<script type="module">
    import { getMessaging, getToken, onMessage } from "https://www.gstatic.com/firebasejs/9.17.2/firebase-messaging.js"
    const messaging = getMessaging()

    requestPermission();

    function sendTokenToServer(currentToken) {
        if (!isTokenSentToServer()) {
            fetch("{% url 'courier:fcm_token_update_api' %}" + `?fcm_token=${currentToken}`)
                .then((data) => {
                    setTokenSentToServer(true);
                }).catch((err) => {
                    console.log(err);
                    setTokenSentToServer(false);
                })

        } else {
            console.log('Token already sent to server so won\'t send it again ' +
                'unless it changes');
        }
    }

    function isTokenSentToServer() {
        return window.localStorage.getItem("sentToServer") === "1";
    }

    function setTokenSentToServer(sent) {
        if (sent) {
            window.localStorage.setItem("sentToServer", "1");
        } else {
            window.localStorage.setItem("sentToServer", "0");
        }
    }


    function requestPermission() {
        Notification.requestPermission().then(function () {
            console.log("Has permission!");
            resetUI();
        }).catch(function (err) {
            console.log('Unable to get permission to notify.', err);
        });
    }

    function resetUI() {
        console.log("In reset ui");
        getToken(
            messaging,
            {
                vapidKey: "{% get_env_var 'FIREBASE_MESSAGING_KEY' %}"
            }
        ).then(function (currentToken) {
            if (currentToken) {
                sendTokenToServer(currentToken);
            } else {
                setTokenSentToServer(false);
            }
        }).catch(function (err) {
            console.log(err);
            setTokenSentToServer(false);
        });
    }

    {% comment %} onTokenRefresh(function () {
        getToken(
            messaging,
            {
                vapidKey: "{% get_env_var 'FIREBASE_MESSAGING_KEY' %}"
            }
        ).then(function (refreshedToken) {
            console.log("Token refreshed.");
            // Indicate that the new Instance ID token has not yet been sent to the
            // app server.
            setTokenSentToServer(false);
            // Send Instance ID token to app server.
            sendTokenToServer(refreshedToken);
            resetUI();
        }).catch(function (err) {
            console.log("Unable to retrieve refreshed token ", err);
        });
    }); {% endcomment %}

    onMessage((payload) => {
        payload = payload.data;
        // Create notification manually when user is focused on the tab
        const notificationTitle = payload.title;
        const notificationOptions = {
            body: payload.body,
            icon: payload.icon_url,
        };

        if (!("Notification" in window)) {
            console.log("This browser does not support system notifications");
        }
        // Let's check whether notification permissions have already been granted
        else if (Notification.permission === "granted") {
            // If it's okay let's create a notification
            var notification = new Notification(notificationTitle, notificationOptions);
            notification.onclick = function (event) {
                event.preventDefault(); // prevent the browser from focusing the Notification's tab
                window.open(payload.url, '_blank');
                notification.close();
            }
        }
        setTimeout(() => {
            window.location.reload()
        }, 5000)
    });


</script>

templates/partials/_meta.html
{% load static %}

<meta name="name" content="Task Rabbit">
<meta name="msapplication-TileColor" content="#C0FFEE">
<meta name="description" content="A simple unobstrusive courier client with a focus on speed of delivery">
<link type="image/png" sizes="32x32" rel="icon" href="{% static 'images/taskrabbit-32.png' %}">
<link rel="icon" type="image/png" sizes="72x72" href="{% static 'images/taskrabbit-72.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/taskrabbit-96.png' %}">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="images/taskrabbit-apple-icon-76.png">