core/customer/urls.py
from django.urls import path
from .views import (
    customer_index,
    customer_profile,
    customer_payment,
    customer_create_job,
    customer_current_jobs,
    customer_archived_jobs,
    JobDetailView,
)

app_name = "customer"

urlpatterns = [
    path("", customer_index, name="home"),
    path("profile/", customer_profile, name="profile"),
    path("payment/", customer_payment, name="payment"),
    path("create-job/", customer_create_job, name="create_job"),
    path("jobs/", customer_current_jobs, name="current_jobs"),
    path("jobs/archived/", customer_archived_jobs, name="archived_jobs"),
    path("jobs/<str:pk>/", JobDetailView.as_view(), name="job_details"),
]

taskrabbit/urls.py
"""
taskrabbit URL Configuration
"""
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from core.views import index, sign_up
import core.customer.urls
import core.courier.urls

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index),
    path("sign-in/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("sign-up", sign_up, name="sign_up"),
    path('accounts/', include('allauth.urls')),
    path("customer/", include(core.customer.urls, namespace="customer")),
    path("courier/", include(core.courier.urls, namespace="courier")),
    path(
        "firebase-messaging-sw.js",
        (
            TemplateView.as_view(
                template_name="firebase-messaging-sw.js",
                content_type="application/x-javascript",
            )
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/customer/forms.py
from django import forms
from django.contrib.auth.models import User

from core.models import Customer, Job


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name"]


class BasicCustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ("avatar",)


class JobCreationForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["name", "description", "category", "size", "quantity", "photo"]


class JobPickupForm(forms.ModelForm):
    pickup_address = forms.CharField(required=True)
    pickup_name = forms.CharField(required=True)
    pickup_phone_number = forms.CharField(required=True)

    class Meta:
        model = Job
        fields = ["pickup_address", "pickup_name", "pickup_phone_number"]


class JobDeliveryForm(forms.ModelForm):
    delivery_address = forms.CharField(required=True)
    delivery_name = forms.CharField(required=True)
    delivery_phone_number = forms.CharField(required=True)

    class Meta:
        model = Job
        fields = ["delivery_address", "delivery_name", "delivery_phone_number"]

core/customer/views.py
import requests
import stripe
import firebase_admin

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import (
    UserProfileForm,
    BasicCustomerForm,
    JobCreationForm,
    JobPickupForm,
    JobDeliveryForm,
)

from core.models import Courier, Job, Transaction

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from firebase_admin import credentials, auth, messaging

if settings.DEBUG == True:
    cred = credentials.Certificate(settings.FIREBASE_ADMIN_CREDENTIALS_PATH)
    firebase_admin.initialize_app(cred)
elif settings.DEBUG == False:
    cred = credentials.Certificate(settings.FIREBASE_ADMIN_CREDENTIALS_DICT)
    firebase_admin.initialize_app(cred)


stripe.api_key = settings.STRIPE_SECRET_KEY


profile_namespace = "customer:profile"
create_job_namespace = "customer:create_job"


@login_required
def customer_index(request):
    return redirect(reverse(profile_namespace))


@login_required(login_url="/sign-in/?next=/customer/")
def customer_profile(request):
    form = UserProfileForm(instance=request.user)
    customer_form = BasicCustomerForm(instance=request.user.customer)
    password_change_form = PasswordChangeForm(request.user)

    if request.method == "POST":
        form = UserProfileForm(request.POST, instance=request.user)
        customer_form = BasicCustomerForm(
            request.POST, request.FILES, instance=request.user.customer
        )
        password_change_form = PasswordChangeForm(request.user, request.POST)
        if request.POST.get("action") == "update_profile":
            if form.is_valid() and customer_form.is_valid():
                form.save()
                customer_form.save()
                messages.success(request, "Your profile has been updated sucessfully!")
                return redirect(reverse(profile_namespace))
        elif request.POST.get("action") == "update_password":
            if password_change_form.is_valid():
                user_password = password_change_form.save()
                update_session_auth_hash(request, user_password)
                messages.success(request, "Your password has been updated sucessfully!")
                return redirect(reverse(profile_namespace))
        elif request.POST.get("action") == "update_phone":
            firebase_user = auth.verify_id_token(request.POST.get("id_token"))
            request.user.customer.phone_number = firebase_user["phone_number"]
            request.user.customer.save()
            return redirect(reverse(profile_namespace))
    return render(
        request,
        "customer/profile.html",
        {
            "form": form,
            "customer_form": customer_form,
            "password_change_form": password_change_form,
        },
    )


@login_required(login_url="/sign-in/?next=/customer/")
def customer_payment(request):
    current_customer = request.user.customer

    if not current_customer.stripe_customer_id:
        customer = stripe.Customer.create()
        current_customer.stripe_customer_id = customer["id"]
        current_customer.save()

    stripe_payment_methods = stripe.PaymentMethod.list(
        customer=current_customer.stripe_customer_id, type="card"
    )

    if stripe_payment_methods and len(stripe_payment_methods.data) > 0:
        payment_method = stripe_payment_methods.data[0]
        current_customer.stripe_payments_method_id = payment_method.id
        current_customer.stripe_card_last_4_digits = payment_method.card.last4
        current_customer.save()
    else:
        current_customer.stripe_payments_method_id = ""
        current_customer.stripe_card_last_4_digits = ""
        current_customer.save()

    if request.method == "POST":
        sp_id = request.user.customer.stripe_payments_method_id
        stripe.PaymentMethod.detach(sp_id)
        current_customer.stripe_payments_method_id = ""
        current_customer.stripe_card_last_4_digits = ""
        current_customer.save()
        return redirect(reverse("customer:payment"))

    if not current_customer.stripe_payments_method_id:
        intent = stripe.SetupIntent.create(
            customer=current_customer.stripe_customer_id,
            payment_method_types=["card"],
        )
        return render(
            request, "customer/payment.html", {"client_secret": intent.client_secret}
        )
    else:
        return render(request, "customer/payment.html")


@login_required(login_url="/sign-in/?next=/customer/")
def customer_create_job(request):
    current_customer = request.user.customer
    current_step = 0

    if not current_customer.stripe_payments_method_id:
        return redirect(reverse("customer:payment"))

    has_current_job = Job.objects.filter(
        customer=current_customer,
        status__in=[Job.PROCESSING, Job.PICKING, Job.DELIVERING],
    ).exists()

    if has_current_job:
        messages.warning(request, "You currently have a processing job!")
        return redirect(reverse("customer:current_jobs"))

    created_jobs = Job.objects.filter(
        customer=current_customer, status=Job.CREATING
    ).last()

    job_creation_form = JobCreationForm(instance=created_jobs)
    job_pickup_form = JobPickupForm(instance=created_jobs)
    job_delivery_form = JobDeliveryForm(instance=created_jobs)

    if request.method == "POST":
        if request.POST.get("step") == "1":
            job_creation_form = JobCreationForm(
                request.POST, request.FILES, instance=created_jobs
            )
            if job_creation_form.is_valid():
                created_jobs = job_creation_form.save(commit=False)
                created_jobs.customer = current_customer
                created_jobs.save()
                return redirect(reverse(create_job_namespace))
        elif request.POST.get("step") == "2":
            job_pickup_form = JobPickupForm(request.POST, instance=created_jobs)
            if job_pickup_form.is_valid():
                created_jobs = job_pickup_form.save()
                return redirect(reverse(create_job_namespace))
        elif request.POST.get("step") == "3":
            job_delivery_form = JobDeliveryForm(request.POST, instance=created_jobs)
            if job_delivery_form.is_valid():
                created_jobs = job_delivery_form.save()
                try:
                    url = (
                        "https://maps.googleapis.com/maps/api/distancematrix/json?origins="
                        + created_jobs.pickup_address
                        + "&destinations="
                        + created_jobs.delivery_address
                        + "&mode=transit&key="
                        + settings.DISTANCE_MATRIX_API_KEY
                    )
                    url = url.replace(" ", "")
                    r = requests.get(url, headers={}, data={})

                    distance = r.json()["rows"][0]["elements"][0]["distance"]["value"]
                    duration = r.json()["rows"][0]["elements"][0]["duration"]["value"]

                    print(distance, duration)
                    created_jobs.distance = round(distance / 1000, 2)
                    created_jobs.duration = int(duration / 60)
                    created_jobs.price = created_jobs.distance * 1

                    created_jobs.save()
                except Exception as e:
                    print(e)
                    messages.error(
                        request,
                        "Unfortunately, we do not support delivery for your location!",
                    )
                return redirect(reverse(create_job_namespace))
        elif request.POST.get("step") == "4":
            if created_jobs.price:
                try:
                    payment_intent = stripe.PaymentIntent.create(
                        amount=int(created_jobs.price * 100),
                        currency="usd",
                        customer=current_customer.stripe_customer_id,
                        payment_method=current_customer.stripe_payments_method_id,
                        off_session=True,
                        confirm=True,
                    )
                    Transaction.objects.create(
                        stripe_payment_intent_id=payment_intent["id"],
                        job=created_jobs,
                        amount=created_jobs.price,
                    )
                    created_jobs.status = Job.PROCESSING
                    created_jobs.save()

                    # send push notification
                    couriers = Courier.objects.all()
                    registration_tokens = [i.fcm_token for i in couriers if i.fcm_token]

                    message = messaging.MulticastMessage(
                        notification=messaging.Notification(
                            title=created_jobs.name,
                            body=created_jobs.description,
                        ),
                        webpush=messaging.WebpushConfig(
                            notification=messaging.WebpushNotification(
                                icon=created_jobs.photo.url
                            ),
                            fcm_options=messaging.WebpushFCMOptions(
                                link=settings.NOTIFICATIONS_URL + reverse('courier:available_jobs'),
                            )
                        ),
                        tokens=registration_tokens
                    )

                    response = messaging.send_multicast(message)

                    print('{0} messages were sent out successfully'.format(response.success.count))

                    return redirect(reverse("customer:home"))

templates/customer/archived-jobs.html
{% extends 'customer/base.html' %}

{% block title %}
    <title>Your Archived Jobs | Task Rabbit</title>
{% endblock title %}

{% block main %}
    <h4>My Archived Jobs</h4>
    {% include 'customer/partials/jobs-navbar.html' %}
    <div class="list-group mt-3">
        {% if jobs %}
            {% for job in jobs  %}
                <a href="{{ job.get_absolute_url }}" class="list-group-item list-group-item-action">
                    <div class="media d-flex justify-content-between mt-4 mb-4">
                        <img style="border-radius: 12px;" class="mr-3" width="100" height="100" src="{{ job.photo.url }}" alt="Image for the job: {{ job.dscription }}">
                        <div style="margin-left: 12px;" class="media-body">
                            <div class="row">
                                <div class="col-lg-9">
                                    <h3 class="mb-1 mt-1">{{ job.name }}</h3>
                                    <p style="font-size: 18px">{{ job.description }}</p>
                                    <div class="d-flex mb-4" title="Pickup Location">
                                        <div>
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M12 14c2.206 0 4-1.794 4-4s-1.794-4-4-4-4 1.794-4 4 1.794 4 4 4zm0-6c1.103 0 2 .897 2 2s-.897 2-2 2-2-.897-2-2 .897-2 2-2z"/><path d="M11.42 21.814a.998.998 0 0 0 1.16 0C12.884 21.599 20.029 16.44 20 10c0-4.411-3.589-8-8-8S4 5.589 4 9.995c-.029 6.445 7.116 11.604 7.42 11.819zM12 4c3.309 0 6 2.691 6 6.005.021 4.438-4.388 8.423-6 9.73-1.611-1.308-6.021-5.294-6-9.735 0-3.309 2.691-6 6-6z"/></svg>
                                        </div>
                                        <div style="margin-left: 12px;" class="d-flex flex-column">
                                            <b style="font-size: 18px">{{ job.pickup_name }}</b>
                                            <small>{{ job.pickup_address }}</small>
                                        </div>
                                    </div>
                                    <div class="d-flex" title="Delivery Location">
                                        <div>
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="m21.447 6.105-6-3a1 1 0 0 0-.895 0L9 5.882 3.447 3.105A1 1 0 0 0 2 4v13c0 .379.214.725.553.895l6 3a1 1 0 0 0 .895 0L15 18.118l5.553 2.776a.992.992 0 0 0 .972-.043c.295-.183.475-.504.475-.851V7c0-.379-.214-.725-.553-.895zM10 7.618l4-2v10.764l-4 2V7.618zm-6-2 4 2v10.764l-4-2V5.618zm16 12.764-4-2V5.618l4 2v10.764z"/></svg>
                                        </div>
                                        <div style="margin-left: 12px;" class="d-flex flex-column">
                                            <b style="font-size: 18px;">{{ job.delivery_name }}</b>
                                            <small>{{ job.delivery_address }}</small>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 text-right d-flex flex-column justify-content-between mt-2">
                                    <div class="mb-2">
                                        <span style="width: fit-content;" class="badge rounded-pill bg-warning text-black">{{ job.get_status_display }}</span>
                                    </div>
                                    <h2 class="mb-1">${{ job.price }}</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <div class="card">
                <div class="card-body text-center">You have no archived jobs yet!</div>
            </div>
        {% endif %}
    </div>
{% endblock main %}

templates/customer/base.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    {% url 'customer:create_job' as create_job_url %}
    {% url 'customer:payment' as pay_url %}
    {% url 'customer:profile' as profile_url %}
    {% url 'customer:current_jobs' as current_jobs_url %}
    {% url 'customer:archived_jobs' as archived_jobs_url %}
    <div class="container bg-light mt-4 pt-3 pb-3">
        <div class="row">
            <div class="col-lg-4">
                <div class="text-center">
                    {% if request.user.customer.avatar %}
                        <img class="rounded-circle mb-2" width="100" height="100" src="{{ request.user.customer.avatar.url }}" alt="Your avatar image">
                    {% else %}
                        <img class="rounded-circle mb-2" width="100" height="100" src="{% static 'images/avatar.png' %}" alt="Your avatar image">
                    {% endif %}
                    <h4>{{ request.user.get_full_name }}</h4>
                    <p class="text-secondary">{{ request.user.email }}</p>
                </div>
                
                <div class="list-group mt-5">
                    <a class="list-group-item list-group-item-action {% if request.path == create_job_url %}active{% endif %}" href="{{ create_job_url }}">
                        Create a Job Posting
                    </a>
                    
                    <a class="list-group-item list-group-item-action {% if request.path ==  current_jobs_url or request.path == archived_jobs_url %}active{% endif %}" href="{{ current_jobs_url }}">
                        My Jobs
                    </a>
                    
                    <a class="list-group-item list-group-item-action {% if request.path == profile_url %}active{% endif %}" href="{{ profile_url }}">
                        Profile Information
                    </a>
                   
                    <a class="list-group-item list-group-item-action {% if request.path == pay_url %}active{% endif %}" href="{{ pay_url }}">
                        Your Payment Method
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                {% block main %}{% endblock  %}
            </div>
        </div>
    </div>
{% endblock  %}

templates/customer/current-jobs.html
{% extends 'customer/base.html' %}

{% block title %}
    <title>Your Current Jobs | Task Rabbit</title>
{% endblock title %}

{% block main %}
    <h4>My Jobs</h4>
    {% include 'customer/partials/jobs-navbar.html' %}

    <div class="list-group mt-3">
        {% if jobs %}
            {% for job in jobs  %}
                <a href="{{ job.get_absolute_url }}" class="list-group-item list-group-item-action">
                    <div class="media d-flex justify-content-between mt-4 mb-4">
                        <img style="border-radius: 12px;" class="mr-3" width="100" height="100" src="{{ job.photo.url }}" alt="Image for the job: {{ job.dscription }}">
                        <div style="margin-left: 12px;" class="media-body">
                            <div class="row">
                                <div class="col-lg-9">
                                    <h3 class="mb-1 mt-1">{{ job.name }}</h3>
                                    <p style="font-size: 18px">{{ job.description }}</p>
                                    <div class="d-flex mb-4" title="Pickup Location">
                                        <div>
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M12 14c2.206 0 4-1.794 4-4s-1.794-4-4-4-4 1.794-4 4 1.794 4 4 4zm0-6c1.103 0 2 .897 2 2s-.897 2-2 2-2-.897-2-2 .897-2 2-2z"/><path d="M11.42 21.814a.998.998 0 0 0 1.16 0C12.884 21.599 20.029 16.44 20 10c0-4.411-3.589-8-8-8S4 5.589 4 9.995c-.029 6.445 7.116 11.604 7.42 11.819zM12 4c3.309 0 6 2.691 6 6.005.021 4.438-4.388 8.423-6 9.73-1.611-1.308-6.021-5.294-6-9.735 0-3.309 2.691-6 6-6z"/></svg>
                                        </div>
                                        <div style="margin-left: 12px;" class="d-flex flex-column">
                                            <b style="font-size: 18px">{{ job.pickup_name }}</b>
                                            <small>{{ job.pickup_address }}</small>
                                        </div>
                                    </div>
                                    <div class="d-flex" title="Delivery Location">
                                        <div>
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="m21.447 6.105-6-3a1 1 0 0 0-.895 0L9 5.882 3.447 3.105A1 1 0 0 0 2 4v13c0 .379.214.725.553.895l6 3a1 1 0 0 0 .895 0L15 18.118l5.553 2.776a.992.992 0 0 0 .972-.043c.295-.183.475-.504.475-.851V7c0-.379-.214-.725-.553-.895zM10 7.618l4-2v10.764l-4 2V7.618zm-6-2 4 2v10.764l-4-2V5.618zm16 12.764-4-2V5.618l4 2v10.764z"/></svg>
                                        </div>
                                        <div style="margin-left: 12px;" class="d-flex flex-column">
                                            <b style="font-size: 18px;">{{ job.delivery_name }}</b>
                                            <small>{{ job.delivery_address }}</small>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 text-right d-flex flex-column justify-content-between mt-2">
                                    <div class="mb-2">
                                        <span style="width: fit-content;" class="badge rounded-pill bg-warning text-black">{{ job.get_status_display }}</span>
                                    </div>
                                    <h2 class="mb-1">${{ job.price }}</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <div class="card">
                <div class="card-body text-center">You have no current jobs yet!</div>
            </div>
        {% endif %}
    </div>
{% endblock main %}

templates/customer/payment.html
{% extends 'customer/base.html' %}
{% load crispy_forms_tags %}
{% load get_env %}

{% block head %}
    {% if not request.user.customer.stripe_payments_method_id %}
        <script src="https://js.stripe.com/v3/"></script>
    {% endif %}
{% endblock head %}

{% block title %}
    <title>Payment | Task Rabbit</title>
{% endblock title %}

{% block main %}
    {% if not request.user.customer.stripe_payments_method_id %}
        <br>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            Let's add your credit/debit card to <strong>Create a Job</strong>!
        </div>
    {% endif %}
    
    {% if request.user.customer.stripe_payments_method_id %}
        <br>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <strong>Card has been saved successfully!</strong>
        </div>
    {% endif %} 

    <br>
    <b class="text-secondary">Your Credit/Dedit card Information</b>
    <p class="form-text text-muted">
        Your card details are never saved in our database
    </p>
    <div class="card bg-white mt-2 mb-5">
        <div class="card-body mt-2">
            {% if request.user.customer.stripe_payments_method_id %}
                <div id="change-card" class="input-group">
                    <input type="text" class="form-control" value="**** **** **** {{ request.user.customer.stripe_card_last_4_digits }}" disabled >
                    <div class="input-group-append">
                        <form method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Remove Card</button>
                        </form>
                    </div>
                </div>
            {% endif %}

            {% if not request.user.customer.stripe_payments_method_id %} 
                <form id="payment-form" data-secret="{{ client_secret }}">
                    <div id="payment-element">
                        
                    </div>
                    <div id="error-message">
                        
                    </div>
                    <br>
                    <button class="btn btn-warning" id="submit">Save Card</button>
                </form>
            {% endif %}
        </div>
    </div>

    <script>
        let alertListBtn = document.querySelectorAll('.alert > button');
        alertListBtn.forEach((btn) => {
            setTimeout(() => {
                btn.click() 
            }, 6000)
        })
    </script>

    {% if not request.user.customer.stripe_payments_method_id %}
        <script type="module">

            const stripe = Stripe("{% get_env_var 'STRIPE_PUBLIC_KEY' %}");
            const options = {
                clientSecret: '{{ client_secret }}',
            };

            // Set up Stripe.js and Elements to use in checkout form, passing the client secret obtained in step 3
            const elements = stripe.elements(options);

            // Create and mount the Payment Element
            const paymentElement = elements.create('payment');
            paymentElement.mount('#payment-element');

            const form = document.getElementById('payment-form');
            form.addEventListener('submit', async (event) => {
                event.preventDefault();

                const {error} = await stripe.confirmSetup({
                    //`Elements` instance that was used to create the Payment Element
                    elements,
                    confirmParams: {
                    return_url: 'http://localhost:8000/customer/payment/',
                    }
                });

                if (error) {
                    const messageContainer = document.querySelector('#error-message');
                    messageContainer.textContent = error.message;
                } else {
                    window.location.reload()
                }
            });
        </script>
    {% endif %}
{% endblock main %}

templates/customer/profile.html
{% extends 'customer/base.html' %}
{% load crispy_forms_tags %}


{% block head %}
    {% include 'partials/_firebase-app.html' %}
{% endblock head %}

{% block title %}
    <title>Profile | Task Rabbit</title>
{% endblock title %}

{% block main %}
    <br>
    <b class="text-secondary">Your Information</b>
    <br>
    <div class="card bg-white mt-2 mb-5">
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                {{ customer_form|crispy }}
                <input type="hidden" name="action" value="update_profile">
                <button type="submit" class="btn btn-warning">Save</button>
            </form>
        </div>
    </div>
    
    <b class="text-secondary">Change Password</b>
    <br>
    <div class="card bg-white mt-2 mb-5">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ password_change_form|crispy }}
                <input type="hidden" name="action" value="update_password">
                <button type="submit" class="btn btn-warning">Update password</button>
            </form>
        </div>
    </div>
    
    <b class="text-secondary">Phone number</b>
    <br>
    <div class="card bg-white mt-2 mb-5">
        <div class="card-body">
            <div id="recaptcha-container"></div>
            
            <div id="get-otp-code" class="input-group mb-3 {% if request.user.customer.phone_number %} d-none {% endif %}">
                <input type="text" name="get_otp" id="get_otp_input" class="form-control" placeholder="Enter your phone number with your country calling code" required>
                <input type="hidden" name="receive" value="verify_phone_number">
                <button type="submit" class="btn btn-warning">Send otp code</button>
            </div>
            <div id="set-otp-code" class="input-group mb-3 d-none">
                <input type="text" name="set_otp" id="set_otp_input" class="form-control" placeholder="Enter your otp verification code" required>
                <input type="hidden" name="verify" value="verify_phone_number">
                <button id="set-otp-btn" type="submit" class="btn btn-warning">Verify otp code</button>
            </div>
            <div id="change-phone" class="input-group mb-3 {% if not request.user.customer.phone_number %} d-none {% endif %}">
                <input type="text" class="form-control" value={{ request.user.customer.phone_number }} disabled>
                <button type="submit" class="btn btn-warning">Change</button>
            </div>
        </div>
    </div>
    {% include 'partials/_firebase-auth.html' %}
{% endblock  %}