core/courier/urls.py
from django.urls import path
from .views import (
    courier_index,
    courier_profile,
    courier_available_jobs,
    courier_available_job,
    courier_current_job,
    courier_current_job_camera,
    courier_job_completed,
    courier_archived_jobs,
    courier_payment_method,
)
from .apis import courier_available_jobs_api, courier_current_job_update_api, courier_fcm_token_update_api

app_name = "courier"

urlpatterns = [
    path("", courier_index, name="home"),
    path("profile/", courier_profile, name="profile"),
    path("payment/", courier_payment_method, name="payment"),
    path("jobs/", courier_available_jobs, name="available_jobs"),
    path("jobs/current/", courier_current_job, name="current_job"),
    path("jobs/completed/", courier_job_completed, name="completed_job"),
    path("jobs/archived/", courier_archived_jobs, name="archived_jobs"),
    path("jobs/<str:pk>/", courier_available_job, name="available_job_details"),
    path(
        "jobs/current/<str:pk>/camera/",
        courier_current_job_camera,
        name="current_job_camera",
    ),
    path("api/jobs/", courier_available_jobs_api, name="available_jobs_api"),
    path(
        "api/jobs/current/<str:pk>/update/",
        courier_current_job_update_api,
        name="current_job_update_api",
    ),
    path(
        "api/fcm-token/update/",
        courier_fcm_token_update_api,
        name="fcm_token_update_api",
    ),
]

taskrabbit/urls.py
"""
taskrabbit URL Configuration
"""
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from core.views import index, sign_up
import core.customer.urls
import core.courier.urls

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index),
    path("sign-in/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("sign-up", sign_up, name="sign_up"),
    path('accounts/', include('allauth.urls')),
    path("customer/", include(core.customer.urls, namespace="customer")),
    path("courier/", include(core.courier.urls, namespace="courier")),
    path(
        "firebase-messaging-sw.js",
        (
            TemplateView.as_view(
                template_name="firebase-messaging-sw.js",
                content_type="application/x-javascript",
            )
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/courier/forms.py
from django import forms

from core.models import Courier


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Courier
        fields = ("paypal_email",)

core/courier/views.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from core.models import Job
from .forms import PaymentForm

available_jobs_namespace = "courier:available_jobs"


@login_required(login_url="/sign-in/?next=/courier/")
def courier_index(request):
    return redirect(reverse(available_jobs_namespace))


@login_required(login_url="/sign-in/?next=/courier/")
def courier_profile(request):
    jobs = Job.objects.filter(courier=request.user.courier, status=Job.COMPLETED)
    total_earnings = sum(job.price for job in jobs) * 0.7
    total_earnings = round(total_earnings, 2)
    total_jobs = len(jobs)
    total_distance = sum(job.distance for job in jobs)
    return render(
        request,
        "courier/profile.html",
        {
            "jobs": jobs,
            "total_earnings": total_earnings,
            "total_jobs": total_jobs,
            "total_distance": total_distance,
        },
    )


@login_required(login_url="/sign-in/?next=/courier/")
def courier_payment_method(request):
    payment_form = PaymentForm(instance=request.user.courier)

    if request.method == "POST":
        payment_form = PaymentForm(request.POST, instance=request.user.courier)
        if payment_form.is_valid():
            payment_form.save()
            messages.success(
                request, "Your payment email has been successfully updated!"
            )
            return redirect(reverse("courier:profile"))
    return render(request, "courier/payment.html", {"payment_form": payment_form})


@login_required(login_url="/sign-in/?next=/courier/")
def courier_available_jobs(request):
    return render(request, "courier/available-jobs.html")


@login_required(login_url="/sign-in/?next=/courier/")
def courier_available_job(request, pk):
    job = Job.objects.filter(id=pk, status=Job.PROCESSING).last()

    if not job:
        return redirect(reverse(available_jobs_namespace))
    if request.method == "POST":
        job.courier = request.user.courier
        job.status = Job.PICKING
        job.save()
        
        try:
            layer = get_channel_layer()
            async_to_sync(layer.group_send)("job_" + str(job.id), {
                "type": "job_update",
                "job": {
                    "status": job.get_status_display(),
                }
            })
        except Exception:
            pass
        return redirect(reverse(available_jobs_namespace))
    return render(request, "courier/available-job-details.html", {"job": job})


@login_required(login_url="/sign-in/?next=/courier/")
def courier_current_job(request):
    job = Job.objects.filter(
        courier=request.user.courier, status__in=[Job.PICKING, Job.DELIVERING]
    ).last()
    return render(request, "courier/current-job.html", {"job": job})


@login_required(login_url="/sign-in/?next=/courier/")
def courier_current_job_camera(request, pk):
    job = Job.objects.filter(
        id=pk, courier=request.user.courier, status__in=[Job.PICKING, Job.DELIVERING]
    ).last()
    if not job:
        return redirect(reverse("courier:current_job"))
    return render(request, "courier/current-job-take-photo.html", {"job": job})


@login_required(login_url="/sign-in/?next=/courier/")
def courier_job_completed(request):
    return render(request, "courier/completed-job.html")


@login_required(login_url="/sign-in/?next=/courier/")
def courier_archived_jobs(request):
    jobs = Job.objects.filter(courier=request.user.courier, status=Job.COMPLETED)
    return render(request, "courier/archived-jobs.html", {"jobs": jobs})

templates/courier/archived-jobs.html
{% extends 'courier/base.html' %}

{% block title %}
    <title>My Archived Jobs | Task Rabbit</title>
{% endblock title %}

{% block head %}
    <style>
        body {
            padding: 0 20px;
        }
        small {
            font-size: 12px;
            line-height: 1.2rem;
        }
    </style>
{% endblock head %}


{% block content %}
    {% include 'courier/partials/bottom-navbar.html' %}
    <div class="d-flex flex-column h-100" style="padding-bottom: 60px">
        <div class="text-center mt-2 mb-1 align-items-center" role="group">
            <a href="{% url 'courier:current_job' %}" class="btn btn-outline-warning">Current Job</a>
            <a href="{% url 'courier:archived_jobs' %}" class="btn btn-warning">Archived Jobs</a>
        </div>
        {% if jobs %}
            {% for job in jobs  %}
            <div style="border: 1.5px solid rgba(0, 0, 0, 0.1); border-radius: 8px;" class="card mx-auto mt-4">
                <div class="card-body p-4 justify-content-center">
                    <div class="media d-flex">
                        <img src="{{ job.photo.url }}" alt="" width="50px" height="50px" style="border-radius: 12px; margin-right: 24px">
                        <div class="media-body ml-4">
                            <b style="font-size: 20px">{{ job.name }}</b>
                            <span style="font-size: 10px;font-weight: 500;background-color: orange;margin-left: 12px;padding:1.5px 6px;border-radius: 12px;">{{ job.get_status_display }}</span>
                            <div class="d-flex justify-content-between">
                                <div class="flex-grow-1 mr-2">
                                    <small class="text-success">
                                        <span>
                                            <svg width='16px' height='16px' fill='#BFBFBF' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                                <path d="M135.2 117.4L109.1 192H402.9l-26.1-74.6C372.3 104.6 360.2 96 346.6 96H165.4c-13.6 0-25.7 8.6-30.2 21.4zM39.6 196.8L74.8 96.3C88.3 57.8 124.6 32 165.4 32H346.6c40.8 0 77.1 25.8 90.6 64.3l35.2 100.5c23.2 9.6 39.6 32.5 39.6 59.2V400v48c0 17.7-14.3 32-32 32H448c-17.7 0-32-14.3-32-32V400H96v48c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32V400 256c0-26.7 16.4-49.6 39.6-59.2zM128 288a32 32 0 1 0 -64 0 32 32 0 1 0 64 0zm288 32a32 32 0 1 0 0-64 32 32 0 1 0 0 64z"/>
                                            </svg>
                                            <span>{{ job.distance }}</span>km
                                        </span>
                                        <span style="margin-left: 16px;">
                                            <svg width='16px' height='16px' fill='#BFBFBF' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                                <path d="M256 0a256 256 0 1 1 0 512A256 256 0 1 1 256 0zM232 120V256c0 8 4 15.5 10.7 20l96 64c11 7.4 25.9 4.4 33.3-6.7s4.4-25.9-6.7-33.3L280 243.2V120c0-13.3-10.7-24-24-24s-24 10.7-24 24z"/>
                                            </svg>
                                            <span>{{ job.duration }}</span>mins
                                        </span>
                                    </small>
                                    <div class="d-flex align-items-center mt-2">
                                        <svg width='20px' height='20px' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                                            <path d="M408 120c0 54.6-73.1 151.9-105.2 192c-7.7 9.6-22 9.6-29.6 0C241.1 271.9 168 174.6 168 120C168 53.7 221.7 0 288 0s120 53.7 120 120zm8 80.4c3.5-6.9 6.7-13.8 9.6-20.6c.5-1.2 1-2.5 1.5-3.7l116-46.4C558.9 123.4 576 135 576 152V422.8c0 9.8-6 18.6-15.1 22.3L416 503V200.4zM137.6 138.3c2.4 14.1 7.2 28.3 12.8 41.5c2.9 6.8 6.1 13.7 9.6 20.6V451.8L32.9 502.7C17.1 509 0 497.4 0 480.4V209.6c0-9.8 6-18.6 15.1-22.3l122.6-49zM327.8 332c13.9-17.4 35.7-45.7 56.2-77V504.3L192 449.4V255c20.5 31.3 42.3 59.6 56.2 77c20.5 25.6 59.1 25.6 79.6 0zM288 152a40 40 0 1 0 0-80 40 40 0 1 0 0 80z"/>
                                        </svg>
                                        <small style="margin-left: 8px;" class="text-secondary ml-2">{{ job.pickup_address }}</small>
                                    </div>
                                    <div class="d-flex align-items-center mt-2">
                                        <svg width='20px' height='20px' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                                            <path d="M32 0C49.7 0 64 14.3 64 32V48l69-17.2c38.1-9.5 78.3-5.1 113.5 12.5c46.3 23.2 100.8 23.2 147.1 0l9.6-4.8C423.8 28.1 448 43.1 448 66.1V345.8c0 13.3-8.3 25.3-20.8 30l-34.7 13c-46.2 17.3-97.6 14.6-141.7-7.4c-37.9-19-81.4-23.7-122.5-13.4L64 384v96c0 17.7-14.3 32-32 32s-32-14.3-32-32V400 334 64 32C0 14.3 14.3 0 32 0zM64 187.1l64-13.9v65.5L64 252.6V318l48.8-12.2c5.1-1.3 10.1-2.4 15.2-3.3V238.7l38.9-8.4c8.3-1.8 16.7-2.5 25.1-2.1l0-64c13.6 .4 27.2 2.6 40.4 6.4l23.6 6.9v66.7l-41.7-12.3c-7.3-2.1-14.8-3.4-22.3-3.8v71.4c21.8 1.9 43.3 6.7 64 14.4V244.2l22.7 6.7c13.5 4 27.3 6.4 41.3 7.4V194c-7.8-.8-15.6-2.3-23.2-4.5l-40.8-12v-62c-13-3.8-25.8-8.8-38.2-15c-8.2-4.1-16.9-7-25.8-8.8v72.4c-13-.4-26 .8-38.7 3.6L128 173.2V98L64 114v73.1zM320 335.7c16.8 1.5 33.9-.7 50-6.8l14-5.2V251.9l-7.9 1.8c-18.4 4.3-37.3 5.7-56.1 4.5v77.4zm64-149.4V115.4c-20.9 6.1-42.4 9.1-64 9.1V194c13.9 1.4 28 .5 41.7-2.6l22.3-5.2z"/>
                                        </svg>
                                        <small style="margin-left: 8px;" class="text-secondary ml-2">{{ job.delivery_address }}</small>
                                    </div>
                                </div>
                                <div style="margin-left: 20px;">
                                    <h3 style="font-size: 32px;">${{ job.price }}</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="d-flex justify-content-center align-items-center text-center h-100" id="main">
                <p style="font-size: 20px;">
                    You have no archived jobs! Let's pick a job
                </p>
            </div>
        {% endif %}
    </div>
{% endblock content %}

templates/courier/completed-job.html
{% extends 'courier/base.html' %} 
{% load static %} 

{% block content %}
    <div class="h-100 d-flex flex-column align-items-center justify-content-center">
    <img
        src="{% static 'images/job-completed.gif' %}"
        alt="Job completed animated image"
        class="mb-3"
        width="300"
        height="300"
    />
    <p style="margin-top: -40px;">Job completed successfully! Well done.</p>
    <a class="btn btn-warning" href="{% url 'courier:home' %}"
        >Go to available jobs</a
    >
    </div>
{% endblock content %}

templates/courier/current-job-take-photo.html
{% extends 'courier/base.html' %}
{% load static %}

{% block title %}
    <title>
        {% if job.get_status_display == 'picking' %}
            Pickup
        {% else %}
            Drop-off
        {% endif %}
         Camera | Task Rabbit
    </title>
{% endblock title %}

{% block head %}
    <script type="text/javascript" src="https://unpkg.com/webcam-easy/dist/webcam-easy.min.js"></script>
    <style>
        body {
            background-color: #121212;
        }
        .btn-back {
            position: fixed;
            top: 30px;
            left: 30px;

        }
        .buttons {
            position: fixed;
            bottom: 20px;
            left: 0;
            right: 0;
            text-align: center;
        }
        #take-photo {
            height: 100%;
            display: flex;
            align-items: center;
        }
        #upload {
            height: 100%;
            display: none;
            align-items: center;
        }
        video {
            width: 100%;
            height: auto;
        }
    </style>
{% endblock head %}

{% block content %}

    <div id="upload">
        <img src="" alt="Pickup Photo" id="photo">
        <div class="buttons">
            <a id="retake-button" style="padding: 8px 8px; background: white; text-decoration: none; color: black" href="javascript:void(retake_photo())">Retake Photo</a>
            <a id="upload-button" style="padding: 8px 8px; background: orange; text-decoration: none; color: black" href="javascript:void(upload_photo())">
                Upload 
                {% if job.get_status_display == 'picking' %}
                    Pickup
                {% else %}
                    Drop-off
                {% endif %}
                Photo
            </a>
        </div>
    </div>
    <div id="take-photo">
        <video id="webcam" autoplay playsinline></video>
        <canvas id="canvas" class="d-none"></canvas>
        <audio id="snapSound" src="{% static 'audio/snap.wav' %}" preload = "auto"></audio>

        <a href="{% url 'courier:current_job' %}" class="btn-back">
            <svg fill="white" xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z"/></svg>
        </a>

        <div class="buttons">
            <a style="padding: 8px 8px; background: orange; text-decoration: none; color: black" href="javascript:void(take_photo())" >
                Take 
                {% if job.get_status_display == 'picking' %}
                    Pickup
                {% else %}
                    Drop-off
                {% endif %}
                Photo
            </a>
        </div>
    </div>
    <script>
        const webcamElement = document.getElementById('webcam');
        const canvasElement = document.getElementById('canvas');
        const snapSoundElement = document.getElementById('snapSound');
        const webcam = new Webcam(webcamElement, 'user', canvasElement, snapSoundElement);
        webcam.start()
        function take_photo() {
            var picture = webcam.snap();
            document.getElementById('photo').setAttribute('src', picture)
            document.getElementById('take-photo').style.display = "none"
            document.getElementById('upload').style.display = "flex"
        }
        function retake_photo() {
            document.getElementById('take-photo').style.display = "flex"
            document.getElementById('upload').style.display = "none"
        }
        function upload_photo() {
            canvasElement.toBlob((blob) => {
                let formData = new FormData()
                let upload_name = "{% if job.get_status_display == 'picking' %}pickup{% else %}delivery{% endif %}"
                let photo_ending = "{{ job.id }}"
                formData.append(`${upload_name}_photo`, blob, `${upload_name}_photo_${photo_ending}.png`)

                fetch("{% url 'courier:current_job_update_api' job.id %}", {
                    method: "POST",
                    body: formData,
                }).then((res) => {
                    return res.json()
                }).then((data) => {
                    if (data.success) {
                        window.location.href = "{% if job.get_status_display == 'picking' %}{% url 'courier:current_job' %}{% else %}{% url 'courier:completed_job' %}{% endif %}"
                    } else {
                        window.reload()
                    }
                })
            })
        }
    </script>
{% endblock content %}

templates/courier/current-job.html
{% extends 'courier/base.html' %}
{% load static %}
{% load get_env %}

{% block title %}
    <title>My Jobs | Task Rabbit</title>
{% endblock title %}

{% block head %}
    <style>
        #map {
            flex: 1;
        }
        small {
            font-size: 12px;
            line-height: 1.2rem;
        }
        .card {
            border: none;
        }
    </style>
{% endblock head %}


{% block content %}
    {% include 'courier/partials/bottom-navbar.html' %}
    <div class="d-flex flex-column h-100" style="padding-bottom: 60px">
        <div class="text-center mt-1 mb-1 align-items-center" role="group">
            <a href="{% url 'courier:current_job' %}" class="btn btn-warning">Current Job</a>
            <a href="{% url 'courier:archived_jobs' %}" class="btn btn-outline-warning">Archived Jobs</a>
        </div>
        {% if job %}
            <div id="map"></div>
            <div class="card">
                <div class="card-body p-4">
                    <div class="media d-flex">
                        <img src="{{ job.photo.url }}" alt="" width="50px" height="50px" style="border-radius: 12px; margin-right: 24px">
                        <div class="media-body ml-4">
                            <b>{{ job.name }}</b>
                            <div class="d-flex justify-content-between">
                                <div class="flex-grow-1 mr-2">
                                    <small class="text-success">
                                        <span>
                                            <svg width='16px' height='16px' fill='#BFBFBF' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                                <path d="M135.2 117.4L109.1 192H402.9l-26.1-74.6C372.3 104.6 360.2 96 346.6 96H165.4c-13.6 0-25.7 8.6-30.2 21.4zM39.6 196.8L74.8 96.3C88.3 57.8 124.6 32 165.4 32H346.6c40.8 0 77.1 25.8 90.6 64.3l35.2 100.5c23.2 9.6 39.6 32.5 39.6 59.2V400v48c0 17.7-14.3 32-32 32H448c-17.7 0-32-14.3-32-32V400H96v48c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32V400 256c0-26.7 16.4-49.6 39.6-59.2zM128 288a32 32 0 1 0 -64 0 32 32 0 1 0 64 0zm288 32a32 32 0 1 0 0-64 32 32 0 1 0 0 64z"/>
                                            </svg>
                                            <span>{{ job.distance }}</span>km
                                        </span>
                                        <span style="margin-left: 16px;">
                                            <svg width='16px' height='16px' fill='#BFBFBF' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                                <path d="M256 0a256 256 0 1 1 0 512A256 256 0 1 1 256 0zM232 120V256c0 8 4 15.5 10.7 20l96 64c11 7.4 25.9 4.4 33.3-6.7s4.4-25.9-6.7-33.3L280 243.2V120c0-13.3-10.7-24-24-24s-24 10.7-24 24z"/>
                                            </svg>
                                            <span>{{ job.duration }}</span>mins
                                        </span>
                                    </small>
                                    <div class="d-flex align-items-center mt-2">
                                        <svg width='20px' height='20px' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                                            <path d="M408 120c0 54.6-73.1 151.9-105.2 192c-7.7 9.6-22 9.6-29.6 0C241.1 271.9 168 174.6 168 120C168 53.7 221.7 0 288 0s120 53.7 120 120zm8 80.4c3.5-6.9 6.7-13.8 9.6-20.6c.5-1.2 1-2.5 1.5-3.7l116-46.4C558.9 123.4 576 135 576 152V422.8c0 9.8-6 18.6-15.1 22.3L416 503V200.4zM137.6 138.3c2.4 14.1 7.2 28.3 12.8 41.5c2.9 6.8 6.1 13.7 9.6 20.6V451.8L32.9 502.7C17.1 509 0 497.4 0 480.4V209.6c0-9.8 6-18.6 15.1-22.3l122.6-49zM327.8 332c13.9-17.4 35.7-45.7 56.2-77V504.3L192 449.4V255c20.5 31.3 42.3 59.6 56.2 77c20.5 25.6 59.1 25.6 79.6 0zM288 152a40 40 0 1 0 0-80 40 40 0 1 0 0 80z"/>
                                        </svg>
                                        <small style="margin-left: 8px;" class="text-secondary ml-2">{{ job.pickup_address }}</small>
                                    </div>
                                    <div class="d-flex align-items-center mt-2">
                                        <svg width='20px' height='20px' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                                            <path d="M32 0C49.7 0 64 14.3 64 32V48l69-17.2c38.1-9.5 78.3-5.1 113.5 12.5c46.3 23.2 100.8 23.2 147.1 0l9.6-4.8C423.8 28.1 448 43.1 448 66.1V345.8c0 13.3-8.3 25.3-20.8 30l-34.7 13c-46.2 17.3-97.6 14.6-141.7-7.4c-37.9-19-81.4-23.7-122.5-13.4L64 384v96c0 17.7-14.3 32-32 32s-32-14.3-32-32V400 334 64 32C0 14.3 14.3 0 32 0zM64 187.1l64-13.9v65.5L64 252.6V318l48.8-12.2c5.1-1.3 10.1-2.4 15.2-3.3V238.7l38.9-8.4c8.3-1.8 16.7-2.5 25.1-2.1l0-64c13.6 .4 27.2 2.6 40.4 6.4l23.6 6.9v66.7l-41.7-12.3c-7.3-2.1-14.8-3.4-22.3-3.8v71.4c21.8 1.9 43.3 6.7 64 14.4V244.2l22.7 6.7c13.5 4 27.3 6.4 41.3 7.4V194c-7.8-.8-15.6-2.3-23.2-4.5l-40.8-12v-62c-13-3.8-25.8-8.8-38.2-15c-8.2-4.1-16.9-7-25.8-8.8v72.4c-13-.4-26 .8-38.7 3.6L128 173.2V98L64 114v73.1zM320 335.7c16.8 1.5 33.9-.7 50-6.8l14-5.2V251.9l-7.9 1.8c-18.4 4.3-37.3 5.7-56.1 4.5v77.4zm64-149.4V115.4c-20.9 6.1-42.4 9.1-64 9.1V194c13.9 1.4 28 .5 41.7-2.6l22.3-5.2z"/>
                                        </svg>
                                        <small style="margin-left: 8px;" class="text-secondary ml-2">{{ job.delivery_address }}</small>
                                    </div>
                                </div>
                                <div style="margin-left: 20px;">
                                    <h3 style="font-size: 32px;">${{ job.price }}</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'courier:current_job_camera' job.id %}" class="btn btn-block btn-warning w-100 mt-2">
                        {% if job.get_status_display == 'picking' %}
                            Pickup
                        {% else %}
                            Drop-off
                        {% endif %}
                    </a>
                </div>
            </div>
        {% else %}
            <div class="d-flex justify-content-center align-items-center text-center h-100" id="main">
                <p style="font-size: 20px;">
                    You have no current job! Let's pick a job
                </p>
            </div>
        {% endif %}
    </div>
    <script>
        const job_id = "{{ job.id }}"
        const user_id = "{{ request.user.id }}"
        const ws_standard = "{% if request.get_host == 'localhost:8000' or request.get_host == '127.0.0.1:8000' %}ws://{% else %}wss://{% endif %}"
        const jobSocket = new WebSocket(
            ws_standard
            + window.location.host
            + '/ws/jobs/'
            + job_id
            + '/'
        );
        

        function updateCourierPosition(map) {
            navigator.geolocation.watchPosition(pos => {
                let courierPosition = new google.maps.LatLng(pos.coords.latitude, pos.coords.longitude)
                if (!window.courierMarker) {
                    window.courierMarker = new google.maps.Marker({
                        position: courierPosition,
                        map,
                    })
                } else {
                    window.courierMarker.setPosition(courierPosition)
                }
                map.panTo(courierPosition)
                try {
                    jobSocket.send(
                        JSON.stringify({
                            job: {
                                user_id: user_id,
                                courier_lat: pos.coords.latitude,
                                courier_lng: pos.coords.longitude
                            }
                        })
                    )
                }
                catch(err) {
                    console.log(err)
                }
            }, pos => console.log(pos))

        }

        function initMap() {
            if (!document.getElementById('map')) {
                return;
            }

            var directionsService = new google.maps.DirectionsService();
            var directionsRenderer = new google.maps.DirectionsRenderer();
            var mapOptions = {
                zoom:5,
                center: { lat: 6.465422, lng: 3.406448 },
            }
            var start = "{{ job.pickup_address }}";
            var end = "{{ job.delivery_address }}";
            var map = new google.maps.Map(document.getElementById('map'), mapOptions);
            var request = {
                origin: start,
                destination: end,
                travelMode: 'DRIVING'
            };
            directionsService.route(request, function(result, status) {
                if (status == 'OK') {
                    directionsRenderer.setDirections(result);
                }
            });
            directionsRenderer.setMap(map);
            
            updateCourierPosition(map)
        }

       
        window.initMap = initMap;
    </script>
    {% if job %}
        <script
        src="https://maps.googleapis.com/maps/api/js?key={% get_env_var 'MAPS_API_KEY' %}&callback=initMap&libraries=places&v=weekly"
        async defer
        ></script>
    {% endif %}
{% endblock content %}