core/courier/urls.py
from django.urls import path
from .views import (
    courier_index,
    courier_profile,
    courier_available_jobs,
    courier_available_job,
    courier_current_job,
    courier_current_job_camera,
    courier_job_completed,
    courier_archived_jobs,
    courier_payment_method,
)
from .apis import courier_available_jobs_api, courier_current_job_update_api, courier_fcm_token_update_api

app_name = "courier"

urlpatterns = [
    path("", courier_index, name="home"),
    path("profile/", courier_profile, name="profile"),
    path("payment/", courier_payment_method, name="payment"),
    path("jobs/", courier_available_jobs, name="available_jobs"),
    path("jobs/current/", courier_current_job, name="current_job"),
    path("jobs/completed/", courier_job_completed, name="completed_job"),
    path("jobs/archived/", courier_archived_jobs, name="archived_jobs"),
    path("jobs/<str:pk>/", courier_available_job, name="available_job_details"),
    path(
        "jobs/current/<str:pk>/camera/",
        courier_current_job_camera,
        name="current_job_camera",
    ),
    path("api/jobs/", courier_available_jobs_api, name="available_jobs_api"),
    path(
        "api/jobs/current/<str:pk>/update/",
        courier_current_job_update_api,
        name="current_job_update_api",
    ),
    path(
        "api/fcm-token/update/",
        courier_fcm_token_update_api,
        name="fcm_token_update_api",
    ),
]

taskrabbit/urls.py
"""
taskrabbit URL Configuration
"""
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from core.views import index, sign_up
import core.customer.urls
import core.courier.urls

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index),
    path("sign-in/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("sign-up", sign_up, name="sign_up"),
    path('accounts/', include('allauth.urls')),
    path("customer/", include(core.customer.urls, namespace="customer")),
    path("courier/", include(core.courier.urls, namespace="courier")),
    path(
        "firebase-messaging-sw.js",
        (
            TemplateView.as_view(
                template_name="firebase-messaging-sw.js",
                content_type="application/x-javascript",
            )
        ),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% include 'partials/_meta.html' %}
    {% block head %}{% endblock head %}
    {% block title %}{% endblock title %}
</head>
<body class="position-relative">
    <nav class="navbar navbar-expand-lg navbar-light bg-warning px-4">
        <div class="container-fluid">
            <div>
                <a style="background-color: white;padding: 6px;" class="navbar-brand d-flex align-items-center rounded-circle" href="/">
                    <img class="rounded-circle" width="28" height="28" src="{% static 'images/taskrabbit-96.png' %}" alt="Task Rabbit Logo">
                </a>
            </div>
        {% if not request.user.is_authenticated %}
            <div>
                <form class="">
                    <button class="btn me-2" type="button">
                        <a class="text-black" style="font-weight: 500; text-decoration: none;" href="{% url 'login' %}?next=/customer/">Login</a>
                    </button>
                    <button style="background: #FFF;" class="btn  " type="button">
                        <a class="text-black" style="text-decoration: none;" href="{% url 'sign_up' %}?next=/customer/">Register</a>
                    </button>
                </form>
            </div>
        {% else %}
            <div>
                <form class="form-inline">
                    <a href="{% url 'logout' %}" class="btn btn-outline-dark">Sign Out</a>
                </form>
            </div>
        {% endif %}
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show w-50 mx-auto my-2" role="alert">
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              <strong>{{ message }}</strong>
            </div>
            
            {% endfor %}
            <script>
              var alertList = document.querySelectorAll('.alert');
              var buttons = document.querySelectorAll('button.btn-close')
              alertList.forEach(function (alert) {
                new bootstrap.Alert(alert)
                buttons.forEach((button) => {
                    setTimeout(() => { button.click() }, 4000)
                })
              })
            </script>
    {% endif %}
    
    {% block content %}{% endblock content %}


    <footer style="position: relative; top: 30vh; padding-bottom: 20px;" class="text-center">
       <p>
           &copy; Taskrabbit 2023
       </p> 
       <p>
           Made with ❤️ & ☕ by Daniel Brai
       </p>
    </footer>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Task Rabbit</title>
{% endblock title %}

{% block head %}
    <style>
        section {
           overflow : hidden;
        }
    </style>
{% endblock head %}
{% block content %}
    <section class="d-flex align-tems-center mt-8">
        <div class="container position-relative">
            <div class="row">
                <div style="margin-top: 80px; margin-bottom: 20px; z-index: 20" class="col-lg-12">
                    <h1 class="text-center">Welcome to Task Rabbit</h1>
                    <p style="font-size: 17px;" class="text-center">A simple, fast and unobstrusive courier client for your deliveries and jobs</p>
                </div>
                <div style="background: transparent; margin-top: -100px;" class="container text-center">
                    <div class="row">
                        <div class="col-sm-12">
                            <img src="{% static 'images/delivery.gif' %}" alt="Taskrabbit Delivery" class="mx-auto img-fluid">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">CUSTOMER</h4>
                            <p class="card-text">
                                Register with us to create a task or service you need done by a courier. 
                                When you register with us, we automatically create a profile that can be used for customer and courier Sign In
                            </p>
                            <a href="{% url 'customer:profile' %}" class="btn btn-warning">Create your profile</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">COURIER</h4>
                            <p class="card-text">
                                Browse available jobs in your location. Choose your best fit!
                            </p>
                            <a href="{% url 'courier:home' %}" class="btn btn-warning">See available jobs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% load crispy_forms_tags %}

{% block head %}
    <style>
        .btn-google {
            color: #545454;
            background-color: #ffffff;
            box-shadow: 0 1px 2px 1px #ddd;
        }

        .or-container {
            align-items: center;
            color: #ccc;
            display: flex;
            margin: 25px 0;
        }

        .line-separator {
            background-color: #ccc;
            flex-grow: 5;
            height: 1px;
        }

        .or-label {
            flex-grow: 1;
            margin: 0 15px;
            text-align: center;
        }
    </style>
{% endblock head %}

{% block title %}
    <title> 
        {% if request.GET.next != '/courier/' %}
            Customer Sign In
        {% else %}
            Courier Sign In
        {% endif %}
        | 
        Task Rabbit
    </title>
{% endblock title %}

{% block content %}

    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="text-center text-upeercase mb-3">
                            {% if request.GET.next != '/courier/' %}
                                Customer Sign In
                            {% else %}
                                Courier Sign In
                            {% endif %}
                        </h4>
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-warning btn-block">Sign In</button>
                            <p class="text-center mt-3">
                                New to Task Rabbit?
                                <a href="{% url 'sign_up' %}?next={{ request.GET.next }}">Sign Up</a>
                            </p>
                        </form>
                        <div class="or-container"><div class="line-separator"></div> <div class="or-label">or</div><div class="line-separator"></div></div>
                        <div class="text-center">
                            <div class="row">
                                <div class="col-md-12">
                                    <a class="btn btn-lg btn-google btn-block btn-outline" href="{% provider_login_url 'google' %}">
                                        <img style="width: 20px; height: 20px;" src="https://img.icons8.com/color/16/000000/google-logo.png"> <span style="font-size: 15px;">Login with Google</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Signup | Task Rabbit</title>
{% endblock title %}

{% block content %}
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="text-center text-uppercase mb-3">
                            Create an account
                        </h4>
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-warning btn-block">Register</button>
                            <p class="text-center mt-3">
                                Already have an account?
                                <a href="{% url 'login' %}?next={{ request.GET.next }}">Sign In</a>
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/signup_done.html
{% extends "base.html" %}
{% block title %}
    <title>
        Sign up success | Task Rabbit 
    </title> 
{% endblock %}
{% block content %}
    <div class="container-fluid mt-5">
        <div class="row text-center">
            <div class="">
                <h1>Welcome {{ user.first_name|default_if_none:user.username }}!</h1>
                <p>
                Your account has been successfully created.
                Now you can <a href="{% url "login" %}">Sign In</a>.
                </p>
            </div>
        </div>
    </div>
{% endblock %}

templates/welcome_email.html
Hi {{ name }}

We're so ecited to have you join us!
Please take a tour of Task Rabbit and see how it can help you.

The Task Tabbit Team
Lagos, Nigeria